<?php

use App\Http\Controllers\AccessController;
use App\Http\Controllers\BrandCatalogueController;
use App\Http\Controllers\BrandCatalogueProductPublishController;
use App\Http\Controllers\BrandController;
use App\Http\Controllers\CatalogueFamilyController;
use App\Http\Controllers\CatalogueImageController;
use App\Http\Controllers\CatalogueSourceController;
use App\Http\Controllers\CatalogueTypeController;
use App\Http\Controllers\CatalogueVariantController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\CategoryScaffoldController;
use App\Http\Controllers\DeliverooProductController;
use App\Http\Controllers\ExportController;
use App\Http\Controllers\ExternalBrandReportController;
use App\Http\Controllers\HairExtensionIntakeController;
use App\Http\Controllers\HairExtensionIntakeWizardController;
use App\Http\Controllers\ImportController;
use App\Http\Controllers\InventoryStructureController;
use App\Http\Controllers\InvoiceGeneratorController;
use App\Http\Controllers\MamadoProductController;
use App\Http\Controllers\MobileCaptureController;
use App\Http\Controllers\MobileCaptureJobController;
use App\Http\Controllers\ObservedBrandMappingController;
use App\Http\Controllers\ObservedPdfMatchController;
use App\Http\Controllers\ObservedProductController;
use App\Http\Controllers\PdfCatalogueProductController;
use App\Http\Controllers\PdfPictureBrandComparisonController;
use App\Http\Controllers\PdfSourceBrandDecisionController;
use App\Http\Controllers\PhotoProcessingSettingController;
use App\Http\Controllers\PictureManagementController;
use App\Http\Controllers\PictureOnlyProductController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\RealBrandController;
use App\Http\Controllers\RealBrandProductController;
use App\Http\Controllers\RetailProductController;
use App\Http\Controllers\RetailProductExportController;
use App\Http\Controllers\RetailProductMediaController;
use App\Http\Controllers\ReviewQueueController;
use App\Http\Controllers\ShabaReferenceController;
use App\Http\Controllers\ShopPhotoBatchController;
use App\Http\Controllers\ShopPhotoController;
use App\Http\Controllers\ShopProductIntakeController;
use App\Http\Controllers\ShopProductNormalizationController;
use App\Http\Controllers\SourceProductController;
use App\Http\Controllers\WatermarkSettingController;
use App\Models\BrandCatalogue;
use App\Support\DeliverooBrands;
use Illuminate\Support\Facades\Route;

Route::get('/access', [AccessController::class, 'choose'])->name('access.choose');
Route::post('/access/data-entry', [AccessController::class, 'enterDataEntry'])->name('access.data-entry');
Route::get('/access/admin', [AccessController::class, 'showAdminGate'])->name('access.admin');
Route::post('/access/admin', [AccessController::class, 'enterAdmin'])->name('access.admin.submit');
Route::post('/access/switch', [AccessController::class, 'switch'])->name('access.switch');
Route::get('/data-entry', [AccessController::class, 'dataEntryDashboard'])->name('data-entry.dashboard');

Route::get('/', [ObservedProductController::class, 'index'])->name('dashboard');
Route::get('/invoice-generator', [InvoiceGeneratorController::class, 'create'])->name('invoice-generator.create');
Route::post('/invoice-generator/pdf', [InvoiceGeneratorController::class, 'pdf'])->name('invoice-generator.pdf');
Route::get('/source-products', [SourceProductController::class, 'index'])->name('source-products.index');
Route::get('/reference/shaba', [ShabaReferenceController::class, 'index'])->name('reference.shaba.index');
Route::get('/reference/shaba/search', [ShabaReferenceController::class, 'search'])->name('reference.shaba.search');
Route::get('/source-products/picture-only', [PictureOnlyProductController::class, 'index'])->name('source-products.picture-only');
Route::get('/source-products/picture-brands', [PictureOnlyProductController::class, 'brands'])->name('source-products.picture-brands');
Route::get('/source-products/picture-brands/{brandKey}', [PictureOnlyProductController::class, 'showBrand'])->name('source-products.picture-brands.show');
Route::get('/products', [ProductController::class, 'index'])->name('products.index');
Route::get('/products/true-products', [ObservedPdfMatchController::class, 'index'])->name('products.true-products');
Route::patch('/products/true-products/price', [ObservedPdfMatchController::class, 'updatePrice'])->name('products.true-products.price');
Route::get('/products/duplicates', [ProductController::class, 'duplicates'])->name('products.duplicates');
Route::post('/products/duplicates/purge', [ProductController::class, 'purgeDuplicates'])->name('products.duplicates.purge');
Route::get('/products/analysis', [ProductController::class, 'analysis'])->name('products.analysis');
Route::get('/products/{observedProduct}', [ProductController::class, 'show'])->name('products.show');
Route::patch('/products/{observedProduct}', [ProductController::class, 'update'])->name('products.update');
Route::post('/products/group-family', [ProductController::class, 'groupFamily'])->name('products.group-family');
Route::post('/products/delete-selected', [ProductController::class, 'deleteSelected'])->name('products.delete-selected');
Route::post('/products/rename-selected', [ProductController::class, 'renameSelected'])->name('products.rename-selected');
Route::post('/observed-products', [ObservedProductController::class, 'store'])->name('observed-products.store');
Route::get('/categories', [CategoryController::class, 'index'])->name('categories.index');
Route::get('/categories/scaffold', [CategoryScaffoldController::class, 'index'])->name('categories.scaffold');
Route::get('/categories/scaffold/sections/{group}', [CategoryScaffoldController::class, 'section'])->name('categories.scaffold.section');
Route::get('/categories/scaffold/roots/{root}', [CategoryScaffoldController::class, 'showRoot'])->name('categories.scaffold.roots.show');
Route::post('/categories/scaffold/roots', [CategoryScaffoldController::class, 'storeRoot'])->name('categories.scaffold.roots.store');
Route::patch('/categories/scaffold/roots/{root}', [CategoryScaffoldController::class, 'updateRoot'])->name('categories.scaffold.roots.update');
Route::post('/categories/scaffold/roots/{root}/axes', [CategoryScaffoldController::class, 'storeAxis'])->name('categories.scaffold.axes.store');
Route::patch('/categories/scaffold/axes/{axis}', [CategoryScaffoldController::class, 'updateAxis'])->name('categories.scaffold.axes.update');
Route::post('/categories/scaffold/roots/{root}/nodes', [CategoryScaffoldController::class, 'storeNode'])->name('categories.scaffold.nodes.store');
Route::patch('/categories/scaffold/nodes/{node}', [CategoryScaffoldController::class, 'updateNode'])->name('categories.scaffold.nodes.update');
Route::get('/categories/{category:slug}', [CategoryController::class, 'show'])->name('categories.show');
Route::get('/categories/{category:slug}/brands', [CategoryController::class, 'brands'])->name('categories.brands');
Route::get('/pictures', [PictureManagementController::class, 'index'])->name('pictures.index');
Route::get('/pictures/unmapped', [PictureManagementController::class, 'unmapped'])->name('pictures.unmapped');
Route::get('/pictures/product-hits', [PictureManagementController::class, 'productHits'])->name('pictures.product-hits');
Route::get('/pictures/{pictureId}', [PictureManagementController::class, 'show'])->name('pictures.show');
Route::get('/pdf-products', [PdfCatalogueProductController::class, 'index'])->name('pdf-products.index');
Route::get('/pdf-products/pages/{page}', [PdfCatalogueProductController::class, 'showPage'])->name('pdf-products.pages.show');
Route::get('/mamado-products', [MamadoProductController::class, 'index'])->name('mamado-products.index');
Route::get('/mamado-products/brands', [MamadoProductController::class, 'brands'])->name('mamado-products.brands');
Route::get('/mamado-products/{mamadoProduct}', [MamadoProductController::class, 'show'])->name('mamado-products.show');
Route::get('/hair-extension-product-intake', [HairExtensionIntakeController::class, 'index'])->name('hair-extension-intake.index');
Route::get('/hair-extension-product-intake/submitted', [HairExtensionIntakeController::class, 'submitted'])->name('hair-extension-intake.submitted');
Route::get('/hair-extension-product-intake/v2', [HairExtensionIntakeController::class, 'v2'])->name('hair-extension-intake.v2');
Route::post('/hair-extension-product-intake/v2', [HairExtensionIntakeController::class, 'submitFamily'])->name('hair-extension-intake.v2.submit');
Route::patch('/hair-extension-product-intake/v2/{intake}', [HairExtensionIntakeController::class, 'updateFamily'])->name('hair-extension-intake.v2.update');
Route::get('/hair-extension-product-intake/wizard', [HairExtensionIntakeWizardController::class, 'index'])->name('hair-extension-intake.wizard.index');
Route::post('/hair-extension-product-intake/wizard', [HairExtensionIntakeWizardController::class, 'store'])->name('hair-extension-intake.wizard.store');
Route::get('/hair-extension-product-intake/wizard/sessions', [HairExtensionIntakeWizardController::class, 'sessions'])->name('hair-extension-intake.wizard.sessions');
Route::get('/hair-extension-product-intake/wizard/{session:session_uuid}', [HairExtensionIntakeWizardController::class, 'show'])->name('hair-extension-intake.wizard.show');
Route::delete('/hair-extension-product-intake/wizard/{session:session_uuid}', [HairExtensionIntakeWizardController::class, 'destroy'])->name('hair-extension-intake.wizard.destroy');
Route::get('/hair-extension-product-intake/wizard/{session:session_uuid}/data', [HairExtensionIntakeWizardController::class, 'load'])->name('hair-extension-intake.wizard.load');
Route::patch('/hair-extension-product-intake/wizard/{session:session_uuid}', [HairExtensionIntakeWizardController::class, 'update'])->name('hair-extension-intake.wizard.update');
Route::post('/hair-extension-product-intake/wizard/{session:session_uuid}/match', [HairExtensionIntakeWizardController::class, 'match'])->name('hair-extension-intake.wizard.match');
Route::post('/hair-extension-product-intake/wizard/{session:session_uuid}/barcode', [HairExtensionIntakeWizardController::class, 'generateBarcode'])->name('hair-extension-intake.wizard.barcode');
Route::post('/hair-extension-product-intake/wizard/{session:session_uuid}/variants', [HairExtensionIntakeWizardController::class, 'upsertVariant'])->name('hair-extension-intake.wizard.variants.upsert');
Route::post('/hair-extension-product-intake/wizard/{session:session_uuid}/variants/mark-unfilled', [HairExtensionIntakeWizardController::class, 'markUnfilledNotInShop'])->name('hair-extension-intake.wizard.variants.mark-unfilled');
Route::post('/hair-extension-product-intake/wizard/{session:session_uuid}/variants/{variant}/photos', [HairExtensionIntakeWizardController::class, 'storePhoto'])->name('hair-extension-intake.wizard.variant-photos.store');
Route::delete('/hair-extension-product-intake/wizard/{session:session_uuid}/variants/{variant}/photos/{photo}', [HairExtensionIntakeWizardController::class, 'destroyPhoto'])->name('hair-extension-intake.wizard.variant-photos.destroy');
Route::get('/hair-extension-product-intake/wizard/{session:session_uuid}/local-review', [HairExtensionIntakeWizardController::class, 'localReview'])->name('hair-extension-intake.wizard.local-review');
Route::post('/hair-extension-product-intake/wizard/{session:session_uuid}/review', [HairExtensionIntakeWizardController::class, 'review'])->name('hair-extension-intake.wizard.review');
Route::post('/hair-extension-product-intake/wizard/{session:session_uuid}/publish', [HairExtensionIntakeWizardController::class, 'publish'])->name('hair-extension-intake.wizard.publish');
Route::post('/hair-extension-product-intake/ai-lookup', [HairExtensionIntakeController::class, 'aiLookup'])->name('hair-extension-intake.ai-lookup');
Route::post('/hair-extension-product-intake/packaging-text', [HairExtensionIntakeController::class, 'packagingText'])->name('hair-extension-intake.packaging-text');
Route::post('/hair-extension-product-intake/autosave', [HairExtensionIntakeController::class, 'autosave'])->name('hair-extension-intake.autosave');
Route::patch('/hair-extension-product-intake/{intake}/autosave', [HairExtensionIntakeController::class, 'autosave'])->name('hair-extension-intake.autosave-existing');
Route::get('/hair-extension-product-intake/{intake}/draft', [HairExtensionIntakeController::class, 'draft'])->name('hair-extension-intake.draft');
Route::get('/hair-extension-product-intake/{intake}/photos', [HairExtensionIntakeController::class, 'photos'])->name('hair-extension-intake.photos');
Route::post('/hair-extension-product-intake/{intake}/photos', [HairExtensionIntakeController::class, 'storePhotos'])->name('hair-extension-intake.photos.store');
Route::post('/hair-extension-product-intake/{intake}/submit', [HairExtensionIntakeController::class, 'submit'])->name('hair-extension-intake.submit');
Route::delete('/hair-extension-product-intake/{intake}', [HairExtensionIntakeController::class, 'destroy'])->name('hair-extension-intake.destroy');
Route::get('/hair-extension-product-intake/submissions.json', [HairExtensionIntakeController::class, 'exportJson'])->name('hair-extension-intake.export-json');
Route::get('/shop-product-intake', [ShopProductIntakeController::class, 'index'])->name('shop-product-intake.index');
Route::post('/shop-product-intake', [ShopProductIntakeController::class, 'store'])->name('shop-product-intake.store');
Route::post('/shop-product-intake/quick-brand', [ShopProductIntakeController::class, 'storeBrand'])->name('shop-product-intake.quick-brand');
Route::post('/shop-product-intake/quick-option', [ShopProductIntakeController::class, 'storeOption'])->name('shop-product-intake.quick-option');
Route::post('/shop-product-intake/suggest-structure', [ShopProductIntakeController::class, 'suggestStructure'])->name('shop-product-intake.suggest-structure');
Route::post('/shop-product-intake/suggest-sku-names', [ShopProductIntakeController::class, 'suggestSkuNames'])->name('shop-product-intake.suggest-sku-names');
Route::get('/shop-product-intake/normalization', [ShopProductNormalizationController::class, 'index'])->name('shop-product-intake.normalization.index');
Route::post('/shop-product-intake/normalization/families', [ShopProductNormalizationController::class, 'storeFamily'])->name('shop-product-intake.normalization.families.store');
Route::post('/shop-product-intake/normalization/families/scratch', [ShopProductNormalizationController::class, 'storeScratchFamily'])->name('shop-product-intake.normalization.families.scratch');
Route::get('/shop-product-intake/submitted', [ShopProductIntakeController::class, 'submitted'])->name('shop-product-intake.submitted');
Route::get('/shop-product-intake/{intake}/edit', [ShopProductIntakeController::class, 'edit'])->name('shop-product-intake.edit');
Route::patch('/shop-product-intake/{intake}', [ShopProductIntakeController::class, 'update'])->name('shop-product-intake.update');
Route::delete('/shop-product-intake/{intake}', [ShopProductIntakeController::class, 'destroy'])->name('shop-product-intake.destroy');
Route::get('/shop-photo-batches', [ShopPhotoBatchController::class, 'index'])->name('shop-photo-batches.index');
Route::get('/shop-photo-batches/{batch}', [ShopPhotoBatchController::class, 'show'])->name('shop-photo-batches.show');
Route::patch('/shop-photo-batches/{batch}/items/{item}', [ShopPhotoBatchController::class, 'updateItem'])->name('shop-photo-batches.items.update');
Route::post('/shop-photo-batches/{batch}/items/{item}/v2-intake', [ShopPhotoBatchController::class, 'createV2Intake'])->name('shop-photo-batches.items.v2-intake');
Route::get('/shop-photo-batches/{batch}/items/{item}/image', [ShopPhotoBatchController::class, 'image'])->name('shop-photo-batches.items.image');
Route::get('/inventory-structure', [InventoryStructureController::class, 'index'])->name('inventory-structure.index');
Route::post('/inventory-structure/stores', [InventoryStructureController::class, 'storeLocation'])->name('inventory-structure.stores.store');
Route::patch('/inventory-structure/stores/{location}', [InventoryStructureController::class, 'updateLocation'])->name('inventory-structure.stores.update');
Route::delete('/inventory-structure/stores/{location}', [InventoryStructureController::class, 'destroyLocation'])->name('inventory-structure.stores.destroy');
Route::post('/inventory-structure/stores/{location}/sections', [InventoryStructureController::class, 'storeSection'])->name('inventory-structure.sections.store');
Route::patch('/inventory-structure/sections/{section}', [InventoryStructureController::class, 'updateSection'])->name('inventory-structure.sections.update');
Route::delete('/inventory-structure/sections/{section}', [InventoryStructureController::class, 'destroySection'])->name('inventory-structure.sections.destroy');
Route::post('/inventory-structure/sections/{section}/subsections', [InventoryStructureController::class, 'storeSubsection'])->name('inventory-structure.subsections.store');
Route::patch('/inventory-structure/subsections/{subsection}', [InventoryStructureController::class, 'updateSubsection'])->name('inventory-structure.subsections.update');
Route::delete('/inventory-structure/subsections/{subsection}', [InventoryStructureController::class, 'destroySubsection'])->name('inventory-structure.subsections.destroy');
Route::get('/deliveroo-products', [DeliverooProductController::class, 'index'])->name('deliveroo-products.index');
Route::get('/deliveroo-products/all', [DeliverooProductController::class, 'allProducts'])->name('deliveroo-products.all');
Route::get('/deliveroo-products/catalogue-pdf', [DeliverooProductController::class, 'cataloguePdf'])->name('deliveroo-products.catalogue-pdf');
Route::get('/deliveroo-products/create', [DeliverooProductController::class, 'createManualProduct'])->name('deliveroo-products.create');
Route::post('/deliveroo-products', [DeliverooProductController::class, 'storeManualProduct'])->name('deliveroo-products.store');
Route::get('/deliveroo-products/api/families', [DeliverooProductController::class, 'familiesForBrandJson'])->name('deliveroo-products.families');
Route::get('/deliveroo-products/api/image-map', [DeliverooProductController::class, 'imageMapForExtension'])->name('deliveroo-products.api.image-map');
Route::get('/deliveroo-products/api/image-proxy/{product}', [DeliverooProductController::class, 'imageProxyForExtension'])->name('deliveroo-products.api.image-proxy');
Route::get('/deliveroo-products/official/{brand}', [DeliverooProductController::class, 'officialBrand'])->name('deliveroo-products.official-brand');
Route::get('/deliveroo-products/official/{brand}/families/{family}', [DeliverooProductController::class, 'officialFamily'])->name('deliveroo-products.official-family');
Route::get('{brand}/families/{family}', [DeliverooProductController::class, 'officialFamily'])
    ->whereIn('brand', DeliverooBrands::slugs())
    ->name('deliveroo-products.official-family.short');
Route::patch('/deliveroo-products/official/{brand}/price', [DeliverooProductController::class, 'updateBrandPrice'])->name('deliveroo-products.official-brand.price');
Route::delete('/deliveroo-products/official/{brand}/products', [DeliverooProductController::class, 'bulkDestroyBrandProducts'])->name('deliveroo-products.official-brand.products.bulk-destroy');
Route::get('/deliveroo-products/official/{brand}/products/{product}/edit', [DeliverooProductController::class, 'editManualProduct'])->name('deliveroo-products.official-product.edit');
Route::get('/deliveroo-products/official/{brand}/products/{product}', [DeliverooProductController::class, 'officialProduct'])->name('deliveroo-products.official-product');
Route::patch('/deliveroo-products/official/{brand}/products/{product}', [DeliverooProductController::class, 'updateManualProduct'])->name('deliveroo-products.official-product.update');
Route::post('/deliveroo-products/official/{brand}/products/{product}/images/upload', [DeliverooProductController::class, 'uploadProductImage'])->name('deliveroo-products.official-product.image-upload');
Route::delete('/deliveroo-products/official/{brand}/products/{product}', [DeliverooProductController::class, 'destroyManualProduct'])->name('deliveroo-products.official-product.destroy');
Route::patch('/deliveroo-products/official/{brand}/products/{product}/price', [DeliverooProductController::class, 'updatePrice'])->name('deliveroo-products.official-product.price');
Route::get('/pdf-brand-decisions', [PdfSourceBrandDecisionController::class, 'index'])->name('pdf-brand-decisions.index');
Route::patch('/pdf-brand-decisions', [PdfSourceBrandDecisionController::class, 'update'])->name('pdf-brand-decisions.update');
Route::post('/pdf-brand-decisions', [PdfSourceBrandDecisionController::class, 'store'])->name('pdf-brand-decisions.store');
Route::patch('/observed-products/{observedProduct}', [ObservedProductController::class, 'update'])->name('observed-products.update');
Route::post('/real-brands', [RealBrandController::class, 'store'])->name('real-brands.store');
Route::patch('/real-brands/{brand}', [RealBrandController::class, 'update'])->name('real-brands.update');
Route::get('/real-brands', [RealBrandController::class, 'index'])->name('real-brands.index');
Route::get('/real-brands/pdf-picture-compare', [PdfPictureBrandComparisonController::class, 'index'])->name('real-brands.pdf-picture-compare');
Route::get('/real-brands/{brand}', [RealBrandController::class, 'show'])->name('real-brands.show');
Route::get('/real-brands/{brand}/product', [RealBrandProductController::class, 'show'])->name('real-brands.products.show');
Route::get('/brand-review', [ObservedBrandMappingController::class, 'index'])->name('brand-review.index');
Route::patch('/brand-mappings/{mapping}', [ObservedBrandMappingController::class, 'update'])->name('brand-mappings.update');
Route::post('/brand-mappings/seed-missing', [ObservedBrandMappingController::class, 'seedMissing'])->name('brand-mappings.seed-missing');
Route::get('/shop-photos/{pictureId}', [ShopPhotoController::class, 'show'])->name('shop-photos.show');
Route::get('/retail-products', [RetailProductController::class, 'index'])->name('retail-products.index');
Route::get('/retail-products/brands', [RetailProductController::class, 'brands'])->name('retail-products.brands');
Route::get('/retail-products/brands/{brandKey}', [RetailProductController::class, 'showBrand'])->name('retail-products.brands.show');
Route::get('/retail-products/families/{family}', [RetailProductController::class, 'showFamily'])->name('retail-products.families.show');
Route::get('/retail-products/families/{family}/export', [RetailProductExportController::class, 'family'])->name('retail-products.families.export');
Route::post('/retail-products/families/{family}/products', [RetailProductController::class, 'storeFamilyProduct'])->name('retail-products.families.products.store');
Route::patch('/retail-products/families/{family}/shared-details', [RetailProductController::class, 'updateFamilySharedDetails'])->name('retail-products.families.shared-details.update');
Route::patch('/retail-products/families/{family}/display-name', [RetailProductController::class, 'updateFamilyDisplayName'])->name('retail-products.families.display-name.update');
Route::patch('/retail-products/families/{family}/variant-pricing', [RetailProductController::class, 'updateFamilyVariantPricing'])->name('retail-products.families.variant-pricing.update');
Route::post('/retail-products/families/{family}/refresh-skus', [RetailProductController::class, 'refreshFamilyMissingSkus'])->name('retail-products.families.refresh-skus');
Route::post('/retail-products/families/{family}/variant-groups', [RetailProductController::class, 'storeFamilyVariantGroup'])->name('retail-products.families.variant-groups.store');
Route::post('/retail-products/families/{family}/variant-groups/{variantGroup}/remove', [RetailProductController::class, 'destroyFamilyVariantGroup'])
    ->name('retail-products.families.variant-groups.destroy')
    ->scopeBindings();
Route::delete('/retail-products/families/{family}/variant-groups/{variantGroup}', [RetailProductController::class, 'destroyFamilyVariantGroup'])
    ->name('retail-products.families.variant-groups.destroy.delete')
    ->scopeBindings();
Route::post('/retail-products/families/{family}/variant-options', [RetailProductController::class, 'storeFamilyVariantOption'])->name('retail-products.families.variant-options.store');
Route::post('/retail-products/families/{family}/variant-options/bulk', [RetailProductController::class, 'storeFamilyVariantOptionsBulk'])->name('retail-products.families.variant-options.bulk-store');
Route::post('/retail-products/families/{family}/variant-options/{option}/create-skus', [RetailProductController::class, 'createSkusForVariantOption'])->name('retail-products.families.variant-options.create-skus');
Route::post('/retail-products/families/{family}/variant-options/create-skus-for-new', [RetailProductController::class, 'createSkusForNewVariantOptions'])->name('retail-products.families.variant-options.create-skus-for-new');
Route::patch('/retail-products/families/{family}/variant-options/{option}', [RetailProductController::class, 'updateFamilyVariantOption'])->name('retail-products.families.variant-options.update');
Route::delete('/retail-products/families/{family}/variant-options/{option}', [RetailProductController::class, 'destroyFamilyVariantOption'])->name('retail-products.families.variant-options.destroy');
Route::delete('/retail-products/families/{family}/variant-options/{option}/skus', [RetailProductController::class, 'destroyFamilySkusForVariantOption'])->name('retail-products.families.variant-options.skus.destroy');
Route::post('/retail-products/families/{family}/variant-options/{option}/split-family', [RetailProductController::class, 'splitFamilyBucketToNewFamily'])->name('retail-products.families.variant-options.split-family');
Route::post('/retail-products/families/{family}/split-families', [RetailProductController::class, 'splitFamilyAllBucketsToNewFamilies'])->name('retail-products.families.split-families');
Route::post('/retail-products/families/{family}/ai-naming/suggest', [RetailProductController::class, 'suggestFamilyNaming'])->name('retail-products.families.ai-naming.suggest');
Route::post('/retail-products/families/{family}/ai-description/suggest', [RetailProductController::class, 'suggestFamilyDescription'])->name('retail-products.families.ai-description.suggest');
Route::patch('/retail-products/families/{family}/ai-naming/apply', [RetailProductController::class, 'applyFamilyNaming'])->name('retail-products.families.ai-naming.apply');
Route::get('/retail-products/products/{product}', [RetailProductController::class, 'showProduct'])->name('retail-products.products.show');
Route::patch('/retail-products/products/{product}/operations', [RetailProductController::class, 'updateProductOperations'])->name('retail-products.products.operations.update');
Route::delete('/retail-products/products/{product}', [RetailProductController::class, 'destroyProduct'])->name('retail-products.products.destroy');
Route::post('/retail-products/families/{family}/media', [RetailProductMediaController::class, 'storeFamily'])->name('retail-products.families.media.store');
Route::post('/retail-products/products/{product}/media', [RetailProductMediaController::class, 'storeProduct'])->name('retail-products.products.media.store');
Route::post('/retail-products/media/{media}/replace', [RetailProductMediaController::class, 'replace'])->name('retail-products.media.replace');
Route::patch('/retail-products/media/{media}', [RetailProductMediaController::class, 'update'])->name('retail-products.media.update');
Route::patch('/retail-products/media/{media}/primary', [RetailProductMediaController::class, 'makePrimary'])->name('retail-products.media.primary');
Route::delete('/retail-products/media/{media}', [RetailProductMediaController::class, 'destroy'])->name('retail-products.media.destroy');

Route::get('/imports/create', [ImportController::class, 'create'])->name('imports.create');
Route::post('/imports', [ImportController::class, 'store'])->name('imports.store');

Route::get('/review', [ReviewQueueController::class, 'index'])->name('review.index');
Route::delete('/brands/{brand}', [BrandController::class, 'destroy'])->name('brands.destroy');
Route::post('/external-brands/{label}/save-brand', [ExternalBrandReportController::class, 'storeBrand'])->name('external-brands.store-brand');
Route::get('/external-brands/{label?}', [ExternalBrandReportController::class, 'show'])->name('external-brands.show');

Route::get('/families/{family}', [CatalogueFamilyController::class, 'show'])->name('families.show');
Route::patch('/families/{family}', [CatalogueFamilyController::class, 'update'])->name('families.update');
Route::post('/families/{family}/approve', [CatalogueFamilyController::class, 'approve'])->name('families.approve');
Route::post('/families/{family}/reject', [CatalogueFamilyController::class, 'reject'])->name('families.reject');
Route::post('/families/{family}/merge', [CatalogueFamilyController::class, 'merge'])->name('families.merge');

Route::post('/families/{family}/types', [CatalogueTypeController::class, 'store'])->name('types.store');
Route::patch('/types/{type}', [CatalogueTypeController::class, 'update'])->name('types.update');
Route::post('/types/{type}/archive', [CatalogueTypeController::class, 'archive'])->name('types.archive');

Route::post('/families/{family}/variants', [CatalogueVariantController::class, 'store'])->name('variants.store');
Route::patch('/variants/{variant}', [CatalogueVariantController::class, 'update'])->name('variants.update');
Route::post('/variants/{variant}/duplicate', [CatalogueVariantController::class, 'duplicate'])->name('variants.duplicate');
Route::post('/variants/{variant}/archive', [CatalogueVariantController::class, 'archive'])->name('variants.archive');

Route::post('/families/{family}/sources', [CatalogueSourceController::class, 'store'])->name('sources.store');
Route::patch('/sources/{source}', [CatalogueSourceController::class, 'update'])->name('sources.update');
Route::delete('/sources/{source}', [CatalogueSourceController::class, 'destroy'])->name('sources.destroy');

Route::post('/images', [CatalogueImageController::class, 'store'])->name('images.store');
Route::patch('/images/{image}', [CatalogueImageController::class, 'update'])->name('images.update');
Route::post('/images/{image}/replace', [CatalogueImageController::class, 'replace'])->name('images.replace');
Route::delete('/images/{image}', [CatalogueImageController::class, 'destroy'])->name('images.destroy');

// Brand Catalogue
Route::get('/brand-catalogue', [BrandCatalogueController::class, 'index'])->name('brand-catalogue.index');
Route::get('/body-care-brand-catalogue', function () {
    $catalogue = BrandCatalogue::query()
        ->where('slug', 'body-care')
        ->orWhere('id', 26)
        ->firstOrFail();

    return redirect()->route('brand-catalogue.show', $catalogue);
})->name('body-care-brand-catalogue');
Route::get('/brand-catalogue/{catalogue}', [BrandCatalogueController::class, 'showCatalogue'])->name('brand-catalogue.show');
Route::get('/brand-catalogue/{catalogue}/product-type-structure', [BrandCatalogueController::class, 'productTypeStructure'])->name('brand-catalogue.product-type-structure');
Route::patch('/brand-catalogue/{catalogue}', [BrandCatalogueController::class, 'updateCatalogue'])->name('brand-catalogue.update');
Route::post('/brand-catalogue/{catalogue}/brands', [BrandCatalogueController::class, 'storeBrand'])->name('brand-catalogue.brands.store');
Route::post('/brand-catalogue/{catalogue}/brand-lines', [BrandCatalogueController::class, 'storeBrandLine'])->name('brand-catalogue.brand-lines.store');
Route::get('/brand-catalogue/{catalogue}/brands/{brand}', [BrandCatalogueController::class, 'showBrand'])->name('brand-catalogue.brands.show');
Route::patch('/brand-catalogue/brands/{brand}', [BrandCatalogueController::class, 'updateBrand'])->name('brand-catalogue.brands.update');
Route::post('/brand-catalogue/brands/{brand}/remove-master-brand', [BrandCatalogueController::class, 'removeMasterBrandLayer'])->name('brand-catalogue.brands.remove-master-brand');
Route::post('/brand-catalogue/brands/{brand}/lines', [BrandCatalogueController::class, 'storeLine'])->name('brand-catalogue.lines.store');
Route::get('/brand-catalogue/{catalogue}/brands/{brand}/lines/{line}', [BrandCatalogueController::class, 'showLine'])->name('brand-catalogue.lines.show');
Route::patch('/brand-catalogue/lines/{line}', [BrandCatalogueController::class, 'updateLine'])->name('brand-catalogue.lines.update');
Route::post('/brand-catalogue/lines/{line}/product-types', [BrandCatalogueController::class, 'storeProductType'])->name('brand-catalogue.product-types.store');
Route::get('/brand-catalogue/{catalogue}/brands/{brand}/lines/{line}/product-types/{productType}', [BrandCatalogueController::class, 'showProductType'])->name('brand-catalogue.product-types.show');
Route::patch('/brand-catalogue/product-types/{productType}', [BrandCatalogueController::class, 'updateProductType'])->name('brand-catalogue.product-types.update');
Route::post('/brand-catalogue/product-types/{productType}/materials', [BrandCatalogueController::class, 'storeMaterial'])->name('brand-catalogue.materials.store');
Route::get('/brand-catalogue/{catalogue}/brands/{brand}/lines/{line}/product-types/{productType}/materials/{material}', [BrandCatalogueController::class, 'showMaterial'])->name('brand-catalogue.materials.show');
Route::patch('/brand-catalogue/materials/{material}', [BrandCatalogueController::class, 'updateMaterial'])->name('brand-catalogue.materials.update');
Route::post('/brand-catalogue/product-types/{productType}/styles', [BrandCatalogueController::class, 'storeStyle'])->name('brand-catalogue.styles.store');
Route::get('/brand-catalogue/{catalogue}/brands/{brand}/lines/{line}/product-types/{productType}/styles/{style}', [BrandCatalogueController::class, 'showStyle'])->name('brand-catalogue.styles.show');
Route::get('/brand-catalogue/{catalogue}/brands/{brand}/lines/{line}/product-types/{productType}/materials/{material}/styles/{style}', [BrandCatalogueController::class, 'showStyleLegacy'])->name('brand-catalogue.styles.show.legacy');
Route::get('/brand-catalogue/{catalogue}/brands/{brand}/lines/{line}/product-types/{productType}/styles/{style}/skus/{sku}', [BrandCatalogueController::class, 'showSku'])->name('brand-catalogue.skus.show');
Route::patch('/brand-catalogue/styles/{style}', [BrandCatalogueController::class, 'updateStyle'])->name('brand-catalogue.styles.update');
Route::post('/brand-catalogue/styles/{style}/variants', [BrandCatalogueController::class, 'storeVariant'])->name('brand-catalogue.variants.store');
Route::post('/brand-catalogue/styles/{style}/variant-matrix', [BrandCatalogueController::class, 'syncVariantMatrix'])->name('brand-catalogue.styles.variant-matrix.sync');
Route::post('/brand-catalogue/styles/{style}/skus', [BrandCatalogueController::class, 'storeSku'])->name('brand-catalogue.skus.store');
Route::post('/brand-catalogue/styles/{style}/publish-products', [BrandCatalogueProductPublishController::class, 'publishStyle'])->name('brand-catalogue.styles.publish-products');
Route::post('/brand-catalogue/variant-options/{option}/publish-retail', [BrandCatalogueProductPublishController::class, 'publishRetailForVariantOption'])->name('brand-catalogue.variant-options.publish-retail');
Route::patch('/brand-catalogue/variants/{variant}', [BrandCatalogueController::class, 'updateVariant'])->name('brand-catalogue.variants.update');
Route::post('/brand-catalogue/variants/{variant}/options', [BrandCatalogueController::class, 'storeVariantOption'])->name('brand-catalogue.variant-options.store');
Route::patch('/brand-catalogue/variant-options/{option}', [BrandCatalogueController::class, 'updateVariantOption'])->name('brand-catalogue.variant-options.update');
Route::patch('/brand-catalogue/skus/{sku}', [BrandCatalogueController::class, 'updateSku'])->name('brand-catalogue.skus.update');
Route::get('/brand-catalogue/{catalogue}/view', [BrandCatalogueController::class, 'viewCatalogue'])->name('brand-catalogue.view');
Route::get('/brand-catalogue/{catalogue}/view/brands/{brand}', [BrandCatalogueController::class, 'viewBrand'])->name('brand-catalogue.view.brand');
Route::get('/brand-catalogue/{catalogue}/view/brands/{brand}/lines/{line}', [BrandCatalogueController::class, 'viewLine'])->name('brand-catalogue.view.line');
Route::get('/brand-catalogue/{catalogue}/view/brands/{brand}/lines/{line}/product-types/{productType}', [BrandCatalogueController::class, 'viewProductType'])->name('brand-catalogue.view.product-type');
Route::get('/brand-catalogue/{catalogue}/view/brands/{brand}/lines/{line}/product-types/{productType}/materials/{material}', [BrandCatalogueController::class, 'viewMaterial'])->name('brand-catalogue.view.material');
Route::get('/brand-catalogue/{catalogue}/view/brands/{brand}/lines/{line}/product-types/{productType}/styles/{style}', [BrandCatalogueController::class, 'viewStyle'])->name('brand-catalogue.view.style');
Route::get('/brand-catalogue/{catalogue}/view/brands/{brand}/lines/{line}/product-types/{productType}/materials/{material}/styles/{style}', [BrandCatalogueController::class, 'viewStyleLegacy'])->name('brand-catalogue.view.style.legacy');
Route::get('/brand-catalogue/{catalogue}/export.json', [BrandCatalogueController::class, 'exportJson'])->name('brand-catalogue.export-json');

// Chrome Extension API
Route::get('/api/brand-catalogue/{catalogue}/scaffolding', [BrandCatalogueController::class, 'apiScaffolding'])->name('api.brand-catalogue.scaffolding');
Route::post('/api/catalogue-capture', [BrandCatalogueController::class, 'apiCaptureStore'])->name('api.catalogue-capture');
Route::options('/api/catalogue-capture', fn () => response('', 204, ['Access-Control-Allow-Origin' => '*', 'Access-Control-Allow-Methods' => 'POST, OPTIONS', 'Access-Control-Allow-Headers' => 'Content-Type, Accept, Authorization']));
Route::options('/api/brand-catalogue/{catalogue}/scaffolding', fn () => response('', 204, ['Access-Control-Allow-Origin' => '*', 'Access-Control-Allow-Methods' => 'GET, OPTIONS', 'Access-Control-Allow-Headers' => 'Content-Type, Accept']));

Route::delete('/brand-catalogue/brands/{brand}', [BrandCatalogueController::class, 'destroyBrand'])->name('brand-catalogue.brands.destroy');
Route::delete('/brand-catalogue/lines/{line}', [BrandCatalogueController::class, 'destroyLine'])->name('brand-catalogue.lines.destroy');
Route::delete('/brand-catalogue/lines-bulk', [BrandCatalogueController::class, 'bulkDestroyLines'])->name('brand-catalogue.lines.bulk-destroy');
Route::delete('/brand-catalogue/product-types/{productType}', [BrandCatalogueController::class, 'destroyProductType'])->name('brand-catalogue.product-types.destroy');
Route::delete('/brand-catalogue/materials/{material}', [BrandCatalogueController::class, 'destroyMaterial'])->name('brand-catalogue.materials.destroy');
Route::delete('/brand-catalogue/styles/{style}', [BrandCatalogueController::class, 'destroyStyle'])->name('brand-catalogue.styles.destroy');
Route::delete('/brand-catalogue/variants/{variant}', [BrandCatalogueController::class, 'destroyVariant'])->name('brand-catalogue.variants.destroy');
Route::delete('/brand-catalogue/variant-options/{option}', [BrandCatalogueController::class, 'destroyVariantOption'])->name('brand-catalogue.variant-options.destroy');
Route::delete('/brand-catalogue/skus/{sku}', [BrandCatalogueController::class, 'destroySku'])->name('brand-catalogue.skus.destroy');
Route::delete('/brand-catalogue/styles/{style}/skus-bulk', [BrandCatalogueController::class, 'bulkDestroySkus'])->name('brand-catalogue.styles.skus.bulk-destroy');

Route::get('/exports', [ExportController::class, 'index'])->name('exports.index');
Route::get('/exports/catalogue-ai-input.csv', [ExportController::class, 'catalogueAiInputCsv'])->name('exports.catalogue-ai-input.csv');
Route::get('/exports/catalogue-ai-input.xlsx', [ExportController::class, 'catalogueAiInputXlsx'])->name('exports.catalogue-ai-input.xlsx');
Route::get('/exports/approved.json', [ExportController::class, 'approvedJson'])->name('exports.approved.json');
Route::get('/exports/approved.csv', [ExportController::class, 'approvedCsv'])->name('exports.approved.csv');

Route::get('/settings/watermark', [WatermarkSettingController::class, 'edit'])->name('settings.watermark.edit');
Route::patch('/settings/watermark', [WatermarkSettingController::class, 'update'])->name('settings.watermark.update');
Route::get('/settings/photo-processing', [PhotoProcessingSettingController::class, 'edit'])->name('settings.photo-processing.edit');
Route::patch('/settings/photo-processing', [PhotoProcessingSettingController::class, 'update'])->name('settings.photo-processing.update');
Route::post('/settings/photo-processing/test', [PhotoProcessingSettingController::class, 'test'])->name('settings.photo-processing.test');
Route::delete('/settings/photo-processing/test-files', [PhotoProcessingSettingController::class, 'clearTests'])->name('settings.photo-processing.test-files.clear');
Route::get('/settings/mobile-capture', [MobileCaptureController::class, 'edit'])->name('settings.mobile-capture.edit');
Route::patch('/settings/mobile-capture', [MobileCaptureController::class, 'update'])->name('settings.mobile-capture.update');
Route::get('/settings/mobile-capture/status', [MobileCaptureController::class, 'status'])->name('settings.mobile-capture.status');
Route::delete('/settings/mobile-capture/uploads', [MobileCaptureController::class, 'destroyAllUploads'])->name('settings.mobile-capture.uploads.destroy-all');
Route::delete('/settings/mobile-capture/uploads/{upload}', [MobileCaptureController::class, 'destroyUpload'])->name('settings.mobile-capture.uploads.destroy');
Route::post('/mobile-capture/jobs', [MobileCaptureJobController::class, 'store'])->name('mobile-capture.jobs.store');
Route::get('/mobile-capture/jobs/{token}/status', [MobileCaptureJobController::class, 'status'])->name('mobile-capture.jobs.status');
Route::get('/mobile-capture/{token}', [MobileCaptureController::class, 'phone'])->name('mobile-capture.phone');
Route::post('/mobile-capture/{token}/heartbeat', [MobileCaptureController::class, 'heartbeat'])->name('mobile-capture.heartbeat');
Route::post('/mobile-capture/{token}/uploads', [MobileCaptureController::class, 'storeUpload'])->name('mobile-capture.uploads.store');
Route::get('/mobile-capture/{token}/jobs', [MobileCaptureJobController::class, 'index'])->name('mobile-capture.jobs.index');
Route::post('/mobile-capture/{token}/jobs/{jobToken}/upload', [MobileCaptureJobController::class, 'upload'])->name('mobile-capture.jobs.upload');
Route::post('/mobile-capture/{token}/jobs/{jobToken}/cancel', [MobileCaptureJobController::class, 'cancel'])->name('mobile-capture.jobs.cancel');
