<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Picture Source Brand Review
    |--------------------------------------------------------------------------
    |
    | These are owner-approved real brands from shop-photo detections. Keep this
    | list separate from alias/merge decisions so brand cleanup is auditable.
    |
    */

    'real_brands_to_keep' => [
        'Activilong',
        "Africa's Best",
        'African Essence',
        'African Pride',
        'Aliza Professional',
        'American Dream',
        'Ampro Pro Styl',
        'ApHogee',
        'As I Am',
        "Aunt Jackie's",
        'Avlon',
        'KeraCare',
        'B.B. Clear',
        'Always Bright',
        'Batiste',
        'Beauty Works Professional',
        'Belle Face',
        'Bigen',
        'Biocare Labs',
        'Bio Claire',
        'Black & White',
        'Blue Magic',
        'Breezy',
        'Bronz Tone',
        'Bump Patrol',
        'Camille Rose',
        'Cantu',
        'Caro Light',
        'Carotone',
        'Clean & Clear',
        'Clear Essence',
        'Clere',
        'Clinic Clear',
        'Clippercide',
        'Crazy Angel',
        'Creative Image Adore',
        'Creme of Nature',
        'CT+ Clear Therapy',
        'CurlyChic',
        'Damatol',
        'Dark & Lovely',
        'DAX',
        'Directions',
        'Disaar',
        'Dodo Skin Gold',
        'Doo Gro',
        'Dr. Meinaier',
        "Dr. Miracle's",
        'Dr. Rashel',
        'Earth Supplied',
        'Ebin New York',
        'Eco Style',
        'Eden BodyWorks',
        'Egyptian Beauty',
        'Elasta QP',
        'Evoke',
        'Extract',
        'Fair & White Paris',
        'Fantasia',
        'Gabri Professional',
        'Gentle Treatment',
        "Ghana's Best",
        'Gluta White',
        'Gold Skin',
        'Gummy Professional',
        'Hair Code',
        'Hawaiian Silky',
        'High Time',
        'Hollywood Beauty',
        'ICAN Nature',
        'IKT',
        'Isoplus',
        'Jamaican Mango & Lime',
        "Jaune d'Oeuf",
        'Jergens',
        "Johnson's",
        'Just For Me',
        'Kemi Organics',
        'Kojic Clear',
        'Kojic White',
        'Kojie San',
        'Kuza',
        "L'abidjanaise",
        "Let's Jam",
        'Long Aid',
        "Luster's Pink",
        "Luster's S Curl",
        'Magno',
        'Makari',
        'Mamado Aromatherapy',
        "Mane 'n Tail",
        'Manic Panic',
        'Mazuri',
        'Mielle',
        'Misba 21',
        'Moco de Gorila',
        "Morgan's Pomade",
        'Motions',
        'MPL',
        "Murray's",
        'Nairobi',
        'Naturelle Bio',
        'Nature Spell',
        'Nature White',
        'Nicka K New York',
        'Nioxin',
        'Nivea',
        'Nuage',
        'Nyxon',
        "Organics by Africa's Best",
        'Original Hair Energizer',
        'ORS',
        'Osmo',
        "Palmer's",
        'Parnevu',
        'Peau Claire',
        'Perfect White',
        'Pierre LaTouche',
        'Piment Doux',
        'Precious Perfect',
        'Pretty White',
        'Pure Skin',
        'Pure White Cosmetics',
        'Pyari',
        'Queen Elisabeth',
        'Queen Helene',
        'Queeny Cazara',
        'Red by Kiss',
        'Red Fox',
        'Red One',
        'Revlon Realistic',
        'Rinju',
        'S-Curl',
        'Salon Grafix',
        'Salon Pro Exclusives',
        'Sauvasine',
        'SheaMoisture',
        "Shine 'n Jam",
        'Silicon Mix',
        'Skala Brasil',
        'Skala Expert',
        "Sof'n'free",
        'Soft & Beautiful',
        "Soft'n White Swiss",
        'SoftSheen-Carson',
        'Sta-Sof-Fro',
        'Style My Edges',
        "Stylin' Dredz",
        'Sulfur8',
        'Sunkissed Skin',
        'Sunny Isle',
        'T444Z',
        'Taliah Waajid',
        'Texture My Way',
        'Tintation',
        'Tomatone',
        'Toujours Jeune',
        'Tropic Isle Living',
        'Tura',
        'Ultra Glow',
        'Vaseline',
        'Vatika',
        'Vatika Naturals',
        'Via Natural',
        'Victoria Super Colorful',
        'Vitale',
        'Wahl Professional',
        'White Secret',
        'Wonder Gro',
        'Yari',
    ],

    /*
    |--------------------------------------------------------------------------
    | Alias/Merge Map
    |--------------------------------------------------------------------------
    |
    | Add aliases here after review. Original observed `brand` is preserved in
    | the row; only `canonical_brand` and optional `brand_line` are updated.
    |
    */

    'aliases' => [
        'African Pride Dream Kids' => ['brand' => 'African Pride', 'line' => 'Dream Kids'],
        "Aunt Jackie's Kids" => ['brand' => "Aunt Jackie's", 'line' => 'Kids'],
        'Avlon KeraCare' => ['brand' => 'KeraCare', 'line' => null],
        'Barber Side' => ['brand' => 'Barberside London', 'line' => null],
        'Barber Side London' => ['brand' => 'Barberside London', 'line' => null],
        'Barberside London' => ['brand' => 'Barberside London', 'line' => null],
        'Dark and Lovely' => ['brand' => 'Dark & Lovely', 'line' => null],
        'Eco' => ['brand' => 'Eco Style', 'line' => null],
        'Just for Me by Soft & Beautiful' => ['brand' => 'Just For Me', 'line' => null],
        'Just For Me Curl Peace' => ['brand' => 'Just For Me', 'line' => 'Curl Peace'],
        'KC by KeraCare' => ['brand' => 'KeraCare', 'line' => null],
        "Kids Originals by Africa's Best" => ['brand' => "Africa's Best", 'line' => 'Kids Originals'],
        "Luster's S Curl" => ['brand' => 'S-Curl', 'line' => null],
        'Motions Professional' => ['brand' => 'Motions', 'line' => 'Professional'],
        'Motions Salon Haircare' => ['brand' => 'Motions', 'line' => 'Salon Haircare'],
        'Organics' => ['brand' => "Organics by Africa's Best", 'line' => null],
        "Originals by Africa's Best" => ['brand' => "Africa's Best", 'line' => 'Originals'],
        'Pink Lemon Braiders' => ['brand' => 'Pink Lemon', 'line' => 'Braiders'],
        'Pro-Line Comb Thru' => ['brand' => 'Pro-Line', 'line' => 'Comb-Thru'],
        'Profectiv Mega Growth' => ['brand' => 'Profectiv', 'line' => 'Mega Growth'],
        'Soft & Beautiful Botanicals' => ['brand' => 'Soft & Beautiful', 'line' => 'Botanicals'],
        'SoftSheen-Carson Magic' => ['brand' => 'SoftSheen-Carson', 'line' => 'Magic'],
        "Swiss Soft 'n' White" => ['brand' => "Soft'n White Swiss", 'line' => null],
        'Taliah Waajid Black Earth Products' => ['brand' => 'Taliah Waajid', 'line' => 'Black Earth Products'],
        'TXTR by Cantu' => ['brand' => 'Cantu', 'line' => 'TXTR'],
        'Ultimate Originals Therapy' => ['brand' => "Africa's Best", 'line' => 'Ultimate Originals Therapy'],
        'Vatika Naturals' => ['brand' => 'Vatika', 'line' => 'Naturals'],
    ],

    'review_aliases' => [
        'Eco Natural' => [
            'options' => ['Eco Style', 'Eco Natural'],
            'reason' => 'Needs packaging confirmation before merge.',
        ],
        'Kojic+' => [
            'options' => ['Kojic White', 'Kojic Clear'],
            'reason' => 'Needs packaging confirmation because multiple targets are possible.',
        ],
        'Original Hair Energizer' => [
            'options' => ['Hair Energizer'],
            'reason' => 'Needs packaging confirmation; use visible packaging name.',
        ],
    ],
];
