<?php

declare(strict_types=1);

use App\Models\BrandCatalogueSku;
use App\Models\BrandCatalogueStyle;
use Illuminate\Contracts\Console\Kernel;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

require __DIR__.'/../vendor/autoload.php';

$app = require __DIR__.'/../bootstrap/app.php';
$app->make(Kernel::class)->bootstrap();

function catalogue_row_id(string $table, array $where, array $data): int
{
    $now = now();
    $exists = DB::table($table)->where($where)->exists();

    DB::table($table)->updateOrInsert(
        $where,
        array_merge($data, [
            'updated_at' => $now,
        ], $exists ? [] : [
            'created_at' => $now,
        ]),
    );

    return (int) DB::table($table)->where($where)->value('id');
}

function parse_variant_parts(?string $text): array
{
    $out = [];

    foreach (explode(';', (string) $text) as $part) {
        $bits = explode(':', trim($part), 2);

        if (count($bits) !== 2) {
            continue;
        }

        $key = trim($bits[0]);
        $value = trim($bits[1]);

        if ($key !== '' && $value !== '') {
            $out[$key] = $value;
        }
    }

    return $out;
}

function sorted_variant_values(array $values): array
{
    $values = array_values(array_unique(array_filter($values, fn ($value): bool => trim((string) $value) !== '')));

    usort($values, function (mixed $a, mixed $b): int {
        if (is_numeric($a) && is_numeric($b)) {
            return ((float) $a) <=> ((float) $b);
        }

        return strnatcasecmp((string) $a, (string) $b);
    });

    return $values;
}

$products = DB::table('mamado_products')
    ->where('brand_label', 'Cherish')
    ->where('family_name', 'Cherish Bulk - Passion Twist')
    ->orderBy('item_code')
    ->get();

if ($products->isEmpty()) {
    throw new RuntimeException('No Cherish Bulk - Passion Twist rows found.');
}

$result = DB::transaction(function () use ($products): array {
    $now = now();

    $brandId = (int) DB::table('brand_catalogue_brands')
        ->where('brand_catalogue_id', 1)
        ->where('name', 'Cherish')
        ->value('id');

    if ($brandId === 0) {
        throw new RuntimeException('Cherish brand is missing from Hair Extensions catalogue.');
    }

    $lineId = catalogue_row_id('brand_catalogue_lines', [
        'brand_catalogue_brand_id' => $brandId,
        'slug' => 'cherish-bulk',
    ], [
        'name' => 'Cherish Bulk',
        'note' => 'Cherish bulk and twist/curl extension lines imported from Mamado source rows.',
        'url' => null,
        'is_default' => false,
        'is_active' => true,
        'sort_order' => 10,
    ]);

    $productTypeId = catalogue_row_id('brand_catalogue_product_types', [
        'brand_catalogue_brand_id' => $brandId,
        'brand_catalogue_line_id' => $lineId,
        'slug' => 'crochet-twist-loc-hair',
    ], [
        'name' => 'Crochet, Twist & Loc Hair',
        'note' => 'Twist, loc, curl, and crochet-friendly extension products. Passion Twist belongs here operationally even when supplier wording includes Bulk.',
        'url' => null,
        'is_active' => true,
        'sort_order' => 20,
    ]);

    $materialId = catalogue_row_id('brand_catalogue_materials', [
        'brand_catalogue_product_type_id' => $productTypeId,
        'slug' => 'synthetic-hair',
    ], [
        'name' => 'Synthetic Hair',
        'note' => 'Synthetic fibre extension material.',
        'url' => null,
        'is_active' => true,
        'sort_order' => 10,
    ]);

    $styleId = catalogue_row_id('brand_catalogue_styles', [
        'brand_catalogue_brand_id' => $brandId,
        'brand_catalogue_product_type_id' => $productTypeId,
        'slug' => 'passion-twist',
    ], [
        'brand_catalogue_material_id' => $materialId,
        'material_name' => 'Synthetic Hair',
        'name' => 'Passion Twist',
        'note' => 'Cherish Bulk Passion Twist family staged from Mamado. Sellable SKUs are generated by length, colour, and bundle where present.',
        'url' => 'http://localhost/LHC_Data/public/mamado-products?brand=Cherish&family=Cherish%20Bulk%20-%20Passion%20Twist&per_page=100',
        'is_active' => true,
        'sort_order' => 10,
    ]);

    $variantConfig = [
        'Length' => ['type' => 'measurement', 'sort' => 10],
        'Colour' => ['type' => 'short_code', 'sort' => 20],
        'Bundle' => ['type' => 'count', 'sort' => 30],
    ];

    $valuesByKey = [];

    foreach ($products as $product) {
        foreach (parse_variant_parts($product->variant_name) as $key => $value) {
            $valuesByKey[$key][] = $value;
        }
    }

    $variantIds = [];
    $optionIds = [];

    foreach ($variantConfig as $key => $config) {
        if (! array_key_exists($key, $valuesByKey)) {
            continue;
        }

        $variantId = catalogue_row_id('brand_catalogue_variants', [
            'brand_catalogue_style_id' => $styleId,
            'name' => $key,
        ], [
            'variant_type' => $config['type'],
            'url' => null,
            'sort_order' => $config['sort'],
        ]);

        $variantIds[$key] = $variantId;

        foreach (sorted_variant_values($valuesByKey[$key]) as $index => $value) {
            $label = ($key === 'Length' && is_numeric($value)) ? $value.' inch' : $value;

            $optionId = catalogue_row_id('brand_catalogue_variant_options', [
                'variant_id' => $variantId,
                'value' => (string) $value,
            ], [
                'label' => (string) $label,
                'sort_order' => ($index + 1) * 10,
            ]);

            $optionIds[$key][(string) $value] = $optionId;
        }
    }

    $firstImage = $products
        ->flatMap(fn (object $product): array => json_decode($product->image_urls ?: '[]', true) ?: [])
        ->filter()
        ->first();

    if ($firstImage) {
        DB::table('catalogue_images')->updateOrInsert([
            'imageable_type' => BrandCatalogueStyle::class,
            'imageable_id' => $styleId,
            'external_url' => $firstImage,
        ], [
            'image_role' => 'main',
            'storage_disk' => null,
            'storage_path' => null,
            'original_filename' => null,
            'mime_type' => null,
            'file_size' => null,
            'sort_order' => 10,
            'is_primary' => true,
            'source_id' => null,
            'notes' => 'Primary image inherited from Mamado Passion Twist source rows.',
            'uploaded_by' => null,
            'updated_at' => $now,
            'created_at' => $now,
        ]);
    }

    $skuCount = 0;
    $imageCount = 0;

    foreach ($products as $index => $product) {
        $parts = parse_variant_parts($product->variant_name);
        $signatureParts = [];

        foreach (['Length', 'Colour', 'Bundle'] as $key) {
            if (isset($parts[$key])) {
                $signatureParts[] = $key.':'.$parts[$key];
            }
        }

        $signature = implode('|', $signatureParts);
        $nameParts = ['Cherish Bulk Passion Twist'];

        if (isset($parts['Bundle'])) {
            $nameParts[] = $parts['Bundle'];
        }

        if (isset($parts['Length'])) {
            $nameParts[] = $parts['Length'].' inch';
        }

        if (isset($parts['Colour'])) {
            $nameParts[] = '- Colour '.$parts['Colour'];
        }

        $skuName = preg_replace('/\s+/', ' ', trim(implode(' ', $nameParts)));

        $skuId = catalogue_row_id('brand_catalogue_skus', [
            'brand_catalogue_style_id' => $styleId,
            'option_signature' => $signature,
        ], [
            'name' => $skuName,
            'slug' => Str::slug($product->item_code ?: $skuName),
            'sku_code' => $product->item_code,
            'barcode' => null,
            'description' => 'Cherish Bulk Passion Twist synthetic hair extension. Variant: '.implode('; ', $signatureParts).'.',
            'note' => 'Imported from Mamado product '.$product->id.' ('.$product->item_description.'). Mamado gross unit price: '.number_format((float) $product->gross_unit_price, 2).'.',
            'url' => 'http://localhost/LHC_Data/public/mamado-products/'.$product->id,
            'is_active' => true,
            'sort_order' => ($index + 1) * 10,
        ]);

        $skuCount++;

        DB::table('brand_catalogue_sku_variant_options')
            ->where('brand_catalogue_sku_id', $skuId)
            ->delete();

        foreach (['Length', 'Colour', 'Bundle'] as $key) {
            if (! isset($parts[$key], $variantIds[$key], $optionIds[$key][(string) $parts[$key]])) {
                continue;
            }

            DB::table('brand_catalogue_sku_variant_options')->updateOrInsert([
                'brand_catalogue_sku_id' => $skuId,
                'brand_catalogue_variant_id' => $variantIds[$key],
                'brand_catalogue_variant_option_id' => $optionIds[$key][(string) $parts[$key]],
            ], [
                'updated_at' => $now,
                'created_at' => $now,
            ]);
        }

        foreach (json_decode($product->image_urls ?: '[]', true) ?: [] as $imageIndex => $imageUrl) {
            if (! $imageUrl) {
                continue;
            }

            DB::table('catalogue_images')->updateOrInsert([
                'imageable_type' => BrandCatalogueSku::class,
                'imageable_id' => $skuId,
                'external_url' => $imageUrl,
            ], [
                'image_role' => $imageIndex === 0 ? 'main' : 'gallery',
                'storage_disk' => null,
                'storage_path' => null,
                'original_filename' => null,
                'mime_type' => null,
                'file_size' => null,
                'sort_order' => ($imageIndex + 1) * 10,
                'is_primary' => $imageIndex === 0,
                'source_id' => null,
                'notes' => 'Mamado image for '.$skuName,
                'uploaded_by' => null,
                'updated_at' => $now,
                'created_at' => $now,
            ]);

            $imageCount++;
        }
    }

    return [
        'brand_id' => $brandId,
        'line_id' => $lineId,
        'product_type_id' => $productTypeId,
        'material_id' => $materialId,
        'style_id' => $styleId,
        'skus' => $skuCount,
        'images' => $imageCount,
        'url' => 'http://localhost/LHC_Data/public/brand-catalogue/1/brands/'.$brandId.'/lines/'.$lineId.'/product-types/'.$productTypeId.'/styles/'.$styleId,
    ];
});

echo json_encode($result, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES).PHP_EOL;
